default: &default
  adapter: postgresql
  encoding: unicode  
  # For details on connection pooling, see Rails configuration guide
  # https://guides.rubyonrails.org/configuring.html#database-pooling
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  username: <%= ENV["POSTGRES_USERNAME"] %>
  password: <%= ENV["POSTGRES_PASSWORD"] %>
  port: 5432

development:
  <<: *default
  database: recipe_app_development


test:
  <<: *default
  database: recipe_app_test


production:
  <<: *default
  database: recipe_app_production


